//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAD08PackagingV1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IndividualPrinter {
            get {
                return ((string)(this["IndividualPrinter"]));
            }
            set {
                this["IndividualPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LAD8N\\LAD8N\\")]
        public string LabelLocation {
            get {
                return ((string)(this["LabelLocation"]));
            }
            set {
                this["LabelLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GroupPrinter {
            get {
                return ((string)(this["GroupPrinter"]));
            }
            set {
                this["GroupPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SCH324")]
        public string AdminPassword {
            get {
                return ((string)(this["AdminPassword"]));
            }
            set {
                this["AdminPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LAD8N\\LAD8N\\LAD8N2.mdb")]
        public string DatabaseReference {
            get {
                return ((string)(this["DatabaseReference"]));
            }
            set {
                this["DatabaseReference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.ACE.OLEDB.12.0")]
        public string ProviderDataBase {
            get {
                return ((string)(this["ProviderDataBase"]));
            }
            set {
                this["ProviderDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LabelIndividualOffsetTop {
            get {
                return ((int)(this["LabelIndividualOffsetTop"]));
            }
            set {
                this["LabelIndividualOffsetTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LabelIndividualOffsetLeft {
            get {
                return ((int)(this["LabelIndividualOffsetLeft"]));
            }
            set {
                this["LabelIndividualOffsetLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LabelGroupOffsetTop {
            get {
                return ((int)(this["LabelGroupOffsetTop"]));
            }
            set {
                this["LabelGroupOffsetTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LabelGroupOffsetLeft {
            get {
                return ((int)(this["LabelGroupOffsetLeft"]));
            }
            set {
                this["LabelGroupOffsetLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string WeighingComName {
            get {
                return ((string)(this["WeighingComName"]));
            }
            set {
                this["WeighingComName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int WeighingComBaudRate {
            get {
                return ((int)(this["WeighingComBaudRate"]));
            }
            set {
                this["WeighingComBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.IO.Ports.Parity WeighingComParity {
            get {
                return ((global::System.IO.Ports.Parity)(this["WeighingComParity"]));
            }
            set {
                this["WeighingComParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public global::System.IO.Ports.StopBits WeighingComStopBit {
            get {
                return ((global::System.IO.Ports.StopBits)(this["WeighingComStopBit"]));
            }
            set {
                this["WeighingComStopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int WeighingComData {
            get {
                return ((int)(this["WeighingComData"]));
            }
            set {
                this["WeighingComData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int WeighingStabilizationTime {
            get {
                return ((int)(this["WeighingStabilizationTime"]));
            }
            set {
                this["WeighingStabilizationTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int WeighingDefaultLimit {
            get {
                return ((int)(this["WeighingDefaultLimit"]));
            }
            set {
                this["WeighingDefaultLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string PLCIpAddress {
            get {
                return ((string)(this["PLCIpAddress"]));
            }
            set {
                this["PLCIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("502")]
        public ushort PLCPort {
            get {
                return ((ushort)(this["PLCPort"]));
            }
            set {
                this["PLCPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PLCScanRate {
            get {
                return ((int)(this["PLCScanRate"]));
            }
            set {
                this["PLCScanRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\LAD8N\\LAD8N\\WorkOderLAD8N.mdb")]
        public string DatabaseWorkOrder {
            get {
                return ((string)(this["DatabaseWorkOrder"]));
            }
            set {
                this["DatabaseWorkOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWorkOrder {
            get {
                return ((string)(this["LastWorkOrder"]));
            }
            set {
                this["LastWorkOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WeighingComSuffix {
            get {
                return ((bool)(this["WeighingComSuffix"]));
            }
            set {
                this["WeighingComSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM2")]
        public string SerialBarcodeComName {
            get {
                return ((string)(this["SerialBarcodeComName"]));
            }
            set {
                this["SerialBarcodeComName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int SerialBarcodeComBaudRate {
            get {
                return ((int)(this["SerialBarcodeComBaudRate"]));
            }
            set {
                this["SerialBarcodeComBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.IO.Ports.Parity SerialBarcodeComParity {
            get {
                return ((global::System.IO.Ports.Parity)(this["SerialBarcodeComParity"]));
            }
            set {
                this["SerialBarcodeComParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public global::System.IO.Ports.StopBits SerialBarcodeComStopBit {
            get {
                return ((global::System.IO.Ports.StopBits)(this["SerialBarcodeComStopBit"]));
            }
            set {
                this["SerialBarcodeComStopBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int SerialBarcodeComData {
            get {
                return ((int)(this["SerialBarcodeComData"]));
            }
            set {
                this["SerialBarcodeComData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int ArticleNumberLength {
            get {
                return ((int)(this["ArticleNumberLength"]));
            }
            set {
                this["ArticleNumberLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSerialBarcode {
            get {
                return ((bool)(this["UseSerialBarcode"]));
            }
            set {
                this["UseSerialBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseBarcodeEntrySuffix {
            get {
                return ((bool)(this["UseBarcodeEntrySuffix"]));
            }
            set {
                this["UseBarcodeEntrySuffix"] = value;
            }
        }
    }
}
